name: Claude-KVM-Daemon
options:
  bundleIdPrefix: com.remrearas.claude-kvm-daemon
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

packages:
  swift-argument-parser:
    url: https://github.com/apple/swift-argument-parser
    from: "1.3.0"

targets:
  claude-kvm-daemon:
    type: tool
    platform: macOS
    sources:
      - ClaudeKVM-Daemon
    dependencies:
      - package: swift-argument-parser
        product: ArgumentParser
    settings:
      base:
        ARCHS: arm64
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        OTHER_SWIFT_FLAGS: "-parse-as-library"
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/vendor/libvnc/prebuilt"
        LIBRARY_SEARCH_PATHS:
          - "$(SRCROOT)/vendor/libvnc/prebuilt"
          - "/opt/homebrew/opt/openssl@3/lib"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/vendor/libvnc/prebuilt/include"
        OTHER_LDFLAGS:
          - "-lvncclient"
          - "-lz"
          - "-lssl"
          - "-lcrypto"
          - "-lpthread"
      configs:
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
