name: Claude-KVM-VLM
options:
  bundleIdPrefix: com.remrearas.claude-kvm-vlm
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

packages:
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm
    minorVersion: "2.29.1"
  swift-argument-parser:
    url: https://github.com/apple/swift-argument-parser
    from: "1.3.0"

targets:
  claude-kvm-vlm:
    type: tool
    platform: macOS
    sources:
      - ClaudeKVM-VLM
    dependencies:
      - package: mlx-swift-lm
        product: MLXVLM
      - package: mlx-swift-lm
        product: MLXLMCommon
      - package: swift-argument-parser
        product: ArgumentParser
    settings:
      base:
        ARCHS: arm64
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        OTHER_SWIFT_FLAGS: "-parse-as-library"
      configs:
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
